---
title: "oriole1"
author: "Lily Goch"
date: "2023-10-23"
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# GWAS in GEMMA ##March 23, 2021

prep beagle files - impute missing data

```{bash, eval=FALSE}
java -Xmx96g -jar /programs/beagle41/beagle41.jar gt=Orioles_filtered_final_093020_55individuals.recode.vcf nthreads=20 out=oriole_beagle_output impute=true
```

# create PLINK files

```{bash, eval=FALSE}
vcftools --gzvcf oriole_beagle_output.vcf.gz --plink --out oriole_outputPlinkformat
```

# make .bed files

```{bash, eval=FALSE}
/programs/plink-1.9-x86_64-beta5/plink --file oriole_outputPlinkformat --make-bed --chr-set 28 no-mt --allow-extra-chr 0 --out oriole_output_bed
```
kept running into error "Invalid chromosome code '27' on line10887551 of .map file. (This is disallowed for humans. Check if the problem is with your data, or if you forgot to define a different chromosome set with e.g. --chr-set.)"

# enter phenotypic information into the .fam file

KEEP TRACK OF COLUMN NUMBERS

N1 = trait one     #haplotype

# RUN GEMMA

[gemma background
manual](https://www.xzlab.org/software/GEMMAmanual.pdf) GEMMA doesn't
seem to like -9 as missing data value. Changing actual missing data to
0. Adding 1 to each plumage score (1-5 instead of 0-4)

# generate relatedness matrix

# 

#gk: specify which type of kinship/relatedness matrix to generate

(default 1; valid value 1-2; 1: centered matrix; 2: standardized
matrix.) ##miss: specify missingness threshold (default 0.05) ##maf:
specify minor allele frequency threshold (default 0.01) ##r2: specify
r-squared threshold (default 0.9999) ##hwe: specify HWE test p value
threshold (default 0; no test)

```{bash, eval=FALSE}
gemma -bfile oriole_output_bed -gk 1 -miss 1 -maf 0 -r2 1 -hwe 0 -o orioles
```

output=GEMMA_HZ

# run GEMMA: univariate linear models

#lmm: linear mixed model (also can run lm or bslmm. read about models
and determine the best option for your data) #lmm (cont): specify
frequentist analysis choice (default 1; valid value 1-4; 1: Wald test;
2: likelihood ratio test; 3: score test; 4: all 1-3.) ##n: specify
phenotype column in the phenotype file (default 1); or to specify which
phenotypes are used in the mvLMM analysis

#Trait one

```{bash, eval=FALSE}
gemma -bfile PATHTO/output_bed -k PAHTTO/GEMMA_HZ.cXX.txt -lmm 4 -n 1 -o
GWAS_HZ_lmm_trait1
```
